### ISSUE TITLE
Request: Pure stand-alone JavaScript (not node.js)

### ISSUE THREAD

**Issue by erosman** [runk/node-maxmind#72]
I am looking for stand-alone JS lib/code if that is possible.

**Comment by runk** [comment]
Are you looking for some sort in-browser solution? It's possible if you'd get the raw buffer with binary database there somehow. Can you give some context?

**Comment by erosman** [comment]
> Are you looking for some sort in-browser solution?

Indeed ..... I wanted to use it for IP -> country queries in a browser (Firefox) extension.

There are already a few that use altered/reconfigured CSV from Maxmind but nothing to directly read mmdb

**Comment by runk** [comment]
If you get the `Buffer`with mmdb db it's possible. Check https://github.com/runk/node-maxmind/blob/master/lib/reader.js#L14. I'm sure there're implementations of `Buffer` module for browser-like environment out there, it's pretty similar to `Uint8Array` that's already available in all modern browsers.

**Comment by erosman** [comment]
Here is an example using generated DAT from Maxmind DB
https://github.com/andy-portmen/country-flags

**Comment by nilfalse** [comment]
Hi @runk

Thank you for your work on this library.

I have recently been curious to learn if it's possible to use your library in the browser with pretty much the same motivation as the topic-starter 🙂 It took me an evening to figure out all the bits and pieces involved but I actually managed to make it work (althrough, it needed some little duct taping).

I've made a gist with my findings, you can find it at https://gist.github.com/d790596bd4728271209d70c9cc2f422f, the outcome turns out to be very short.

It actually works, I put a live version available at https://nilfalse.com/labs/geoip/

My question is, would you consider re-opening this issue so we could discuss improving the API for browsers? I think we could get rid of most of the workarounds I needed to implement in my gist.

PS. I've tried to explain the steps involved in a post here https://ilin.dk/weblog/maxmind-in-browser, if anyone is as curious.

**Comment by runk** [comment]
Given fair bit of interest, issue is re-opened now.

We can look into splitting this repo into several independent ones 
 - Library for working with mmdb
 - Library for node.js / browser

**Comment by nilfalse** [comment]
That's super awesome to hear! Thank you for reopening this issue.

Would you be kind to elaborate what exactly do you have on your mind?
I think you are right that in the long run this library can potentially be split up into 2 separate modules, but do you think we could **start with some low-hanging fruits**?

I thought as a very first thing just to get started we could add a separate entry point just for browser consumers.
1. It really is just a matter of referencing it in the `package.json` `"browser"` field in order to make it work out of the box at least for webpack users (see https://webpack.js.org/configuration/resolve/#resolvemainfields).
2. This has to expose the plain `Reader` class at least. The module also must not import `fs` or `net`.
3. Ideally that `Reader` should also use a subclass of `Decoder` that specifically does not use that [undocumented `Buffer` method](https://github.com/runk/node-maxmind/blob/47e4eb7f/src/decoder.ts#L320-L326), but I can address this in a later PR.

I believe that eventually this library might be ported over to use standard `ArrayBuffer` instead of the Node.js'es `Buffer` in order to be compatible with more environments (think of Deno also?), but that seems to be a big chunk of work. Please, correct me if I'm wrong 🙂 

I'm happy to prepare a PR to address bullets 1) and 2) from above.
Let me know what you think.

**Comment by runk** [comment]
Alright, I gave it a crack. 

https://github.com/runk/mmdb-lib

Still early days and feedback/contributions would be highly appreciated.

**Comment by runk** [comment]
cc @nilfalse ☝️

**Comment by nilfalse** [comment]
Just to be clear, what's your plan for that new library? Do you plan to incorporate it as a dependency into this repository in the longer term?

**Comment by runk** [comment]
Yeah, that's the plan. Just matter of finding a couple of hrs and actually doing it.

**Comment by runk** [comment]
https://github.com/runk/mmdb-lib
